name: contextworkflow

on:
  push:
    branches:
      - main

jobs:
  contexjobs:
    runs-on: windows-latest
    steps:
      - name: print context variable for evnets
        run: echo "print the which type of events ${{ github.event_name }}"
      - name: print repostrty
        run: echo "print the repostirt ${{ github.repository }}"
      - name: print repostrty
        run: echo "print the repostirt ${{ github.base_ref }}"  
        
        
