name: enviromentworkflow

on:
  workflow_dispatch:
env:
 NAME: srinu

jobs:
   environemntvar:
       runs-on: ubuntu-latest
       env:
         NAME: priya
         SECOND: srinu
       steps: 
         - name: vaiableconfiguriaon
           run: echo "this is printing variable $NAME"
         - name: want to print one more vatiable
           run: echo "this is printing second stage $SECOND"
         
 
   
