name: enviromentworkflow

on:
  workflow_dispatch:


jobs:
   environemntvar:
       runs-on: ubuntu-latest
       env:
        NAME: priya
       steps: 
         - name: vaiableconfiguriaon
           run: echo "this is printing variable $NAME"
        
         
 
   
