name: givetheinputs
on:
  workflow_dispatch:
   inputs:
    version:
       description: select the docker version
       required: true 
       type: string
          
jobs:
  inputtrigger:
     runs-on: ubuntu-latest
     steps:
       - name: printtheenvironment
         run: echo "print the envornemnt ${{ inputs.version }}"
    
  
  
