name: outputworkflow

on:
  push:
    branches:
      - main
jobs:
  contexjobs:
    runs-on: ubuntu-latest
    steps:
      - name: echo print stageone
        id: step1
        run: echo "version=1.0.0" >> $GITHUB_OUTPUT
      - name: usetheoutput
        run: echo "this is version ${{ steps.step1.outputs.version }}"
        
        
    
    
