name: s3-bucket-upload

on:
  workflow_dispatch

jobs:
  s3uploadobject:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: configure the aws creditonals
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id:
         aws-secret-access-key:
         region: us-east-1
          
        
         
     
        
