name: student-registration-ci-workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        run: echo "print ${{ vars.NAME }}"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing package
        run: echo "print ${{ vars.NAME }}"

  secrets-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret
        run: echo "print token ${{ secrets.TOKEN }}"

  docker-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code   # 👈 MUST
        uses: actions/checkout@v4

      - name: Display Dockerfile
        run: cat Dockerfile
